[package]
name = "org_ownership_investigation"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.20"
nom = "7.1.1"
tokio = { version = "1.30.0", default-features = false, features = ["rt", "rt-multi-thread"] }
